/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as homePageIndexRouteImport } from './routes/(home-page)/index'

const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const homePageIndexRoute = homePageIndexRouteImport.update({
  id: '/(home-page)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homePageIndexRoute
  '/menu': typeof MenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homePageIndexRoute
  '/menu': typeof MenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home-page)/': typeof homePageIndexRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/menu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/menu'
  id: '__root__' | '/(home-page)/' | '/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homePageIndexRoute: typeof homePageIndexRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home-page)/': {
      id: '/(home-page)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homePageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homePageIndexRoute: homePageIndexRoute,
  MenuIndexRoute: MenuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
